# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88ab45a01b0befbcf93d0918d05899ca42f317ce0094c20f964a30d1b58c999f2ee8903ba6f288be5c8f53a9d5b0de2160c751dedb3b0baf056a6142a8b046a

test:
  secret_key_base: e096844d3c7523b2e893b35a63b1e21c6f367f569bd9d87fc01fed15b5ae4ededd8b3f6e23382786f625ca8d3585c0ced2b08678467f6663d86bb5836fd52d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
